import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

type Params={params:Promise<{enrollmentStudentId:string}>};
const fields=["communication_expression","speaking_interaction","vocabulary_expression_range","grammar_sentence_building","pronunciation_clarity","confidence_participation","overall_progress","next_focus","teacher_note"] as const;
async function access(enrollmentStudentId:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {error:NextResponse.json({error:"Unauthorized"},{status:401})};const admin=createAdminClient();const {data:profile}=await admin.from("profiles").select("id,role,status").eq("id",user.id).maybeSingle();if(!profile||profile.role!=="teacher"||profile.status!=="active")return {error:NextResponse.json({error:"Only active teachers can access progress reports."},{status:403})};const {data:assignment}=await admin.from("teacher_assignments").select("id").eq("teacher_id",user.id).eq("enrollment_student_id",enrollmentStudentId).eq("status","active").maybeSingle();if(!assignment)return {error:NextResponse.json({error:"This student is not assigned to you."},{status:403})};return {admin,user,error:null};}
export async function GET(_r:Request,{params}:Params){const {enrollmentStudentId}=await params;const a=await access(enrollmentStudentId);if(a.error)return a.error;const {data,error}=await a.admin!.from("progress_reports").select("*").eq("enrollment_student_id",enrollmentStudentId).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({report:data});}
export async function PUT(request:Request,{params}:Params){const {enrollmentStudentId}=await params;const a=await access(enrollmentStudentId);if(a.error)return a.error;const body=await request.json();const status=body?.status==="completed"?"completed":"draft";const payload:any={enrollment_student_id:enrollmentStudentId,teacher_id:a.user!.id,status,updated_at:new Date().toISOString(),completed_at:status==="completed"?new Date().toISOString():null};for(const f of fields)payload[f]=typeof body?.[f]==="string"?body[f].trim():"";const {data,error}=await a.admin!.from("progress_reports").upsert(payload,{onConflict:"enrollment_student_id"}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({report:data});}
